In [1]:
from recsys import * ## recommender system cookbook
from generic_preprocessing import * ## pre-processing code
from IPython.display import HTML ## Setting display options for Ipython Notebook

/anaconda3/lib/python3.6/site-packages/lightfm/_lightfm_fast.py:9: UserWarning: LightFM was compiled without OpenMP support. Only a single thread will be used.
  warnings.warn('LightFM was compiled without OpenMP support. '

In [2]:
# Importing rating data and having a look
ratings = pd.read_csv('ratings.csv')

#ratings.columns= ['UserId','PackageId','Rating','timestamp']

# Importing movie data and having a look at first five columns
packages = pd.read_csv('packages.csv')
#packages = pd.DataFrame(d,columns=['ID','title','Duration'])

In [4]:
ratings.head()

   Unnamed: 0  UserId  PackageId  Rating   timestamp
0           0       1         52     2.5  1260759144
1           1       1        217     3.0  1260759179
2           2       1        339     3.0  1260759182
3           3       1        233     2.0  1260759185
4           4       1        448     4.0  1260759205

In [5]:
# Creating interaction matrix using rating data
interactions = create_interaction_matrix(df = ratings,
                                         user_col = 'UserId',
                                         item_col = 'PackageId',
                                         rating_col = 'Rating')
interactions.head()

PackageId,1,2,3,4,5,6,7,8,9,10,...,518,519,520,521,522,523,524,525,526,527
UserId,,,,,,,,,,,,,,,,,,,,,
1,0.0,3.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
2,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,5.0,0.0,3.0,5.0,0.0,4.0,0.0,0.0,...,0.0,3.0,0.0,3.0,0.0,0.0,0.0,0.0,8.0,7.0
5,0.0,0.0,0.0,4.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0

In [10]:
# Create User Dict
user_dict = create_user_dict(interactions=interactions)
# Create Item dict
packages_dict = create_item_dict(df = packages,
                               id_col = 'ID',
                               name_col = 'title')

In [11]:
mf_model = runMF(interactions = interactions,
                 n_components = 30,
                 loss = 'warp',
                 epoch = 30,
                 n_jobs = 4)

In [13]:
## Calling 10 movie recommendation for user id 2
rec_list = sample_recommendation_user(model = mf_model, 
                                      interactions = interactions, 
                                      user_id = 2, 
                                      user_dict = user_dict,
                                      item_dict = packages_dict, 
                                      threshold = 4,
                                      nrec_items = 5,
                                      show = True)

Known Likes:
1- Everest Base Camp Trek
2- Epic Nepal To India
3- GHT Rara Lake & Yari Valley
4- Make Your Own Souvenir
5- Wonders Of Southern Nepal By Bicycle
6- Exploring Patan And Bhaktapur: Kathmandu Valleyâ€™s Other Kingdoms
7- Nepal: Hike Bike & Raft
8- 10 Days Sunkoshi River Rafting Tour
9- 1 Hour Mountain Flight
10- Yala Peak Climbing Adventure
11- Sunrise View From Sarangkot
12- Temples And Monasteries
13- Ghandruk Loop Trek From Pokhara
14- Gokyo And Everest Base Camp Trek
15- 9 Day Everest Base Camp Trek With Chopper Return

 Recommended Items:
1- Everest Base Camp - 3 Passes Adventure Trek
2- Lobuche East & Pokalde Peak
3- Chitwan Jungle Safari - 2 Nights And 3 Days
4- Makalu Base Camp
5- Everest Base Camp Helicopter Tour